# Generated by Django 3.1.2 on 2021-09-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_shopkeeper',
        ),
        migrations.DeleteModel(
            name='ShopKeeperProfile',
        ),
    ]
